apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-node
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-node
  template:
    metadata:
      labels:
        app: test-node
    spec:
      containers:
      - name: test-node
        image: gcr.io/smartleep-app/test-node
        imagePullPolicy: Always
