apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-kluster
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-kluster
  template:
    metadata:
      labels:
        app: test-kluster
    spec:
      containers:
      - name: test-kluster
        image: gcr.io/smartleep-app/test-kluster
        imagePullPolicy: Always
        
