apiVersion: apps/v1
kind: Deployment
metadata:
  name: testnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: testnode
  template:
    metadata:
      labels:
        app: testnode
    spec:
      containers:
      - image: gcr.io/smartleep-app/test-node
        name: app
        imagePullPolicy: Always
        
